-- Paystubs: a snapshot of each month's pay, generated by an Accountant/Admin.
-- Deductions are entered manually (a total + a free-text note describing
-- what they cover) rather than auto-calculated, since Nigerian statutory
-- withholding formulas (PAYE tax, pension, NHF) need to be verified by an
-- accountant before being encoded - see README for the phased plan.

CREATE TABLE IF NOT EXISTS paystubs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    staff_id UUID REFERENCES staff(id) ON DELETE CASCADE NOT NULL,
    pay_period_month INTEGER NOT NULL CHECK (pay_period_month BETWEEN 1 AND 12),
    pay_period_year INTEGER NOT NULL,
    basic_salary NUMERIC(12,2) NOT NULL DEFAULT 0,
    housing_allowance NUMERIC(12,2) NOT NULL DEFAULT 0,
    transport_allowance NUMERIC(12,2) NOT NULL DEFAULT 0,
    utility_allowance NUMERIC(12,2) NOT NULL DEFAULT 0,
    meal_allowance NUMERIC(12,2) NOT NULL DEFAULT 0,
    gross_pay NUMERIC(12,2) NOT NULL DEFAULT 0,
    deductions NUMERIC(12,2) NOT NULL DEFAULT 0,
    deductions_note TEXT,
    net_pay NUMERIC(12,2) NOT NULL DEFAULT 0,
    currency VARCHAR(3) DEFAULT 'NGN',
    generated_by UUID REFERENCES staff(id) ON DELETE SET NULL,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(staff_id, pay_period_month, pay_period_year)
);

CREATE INDEX IF NOT EXISTS idx_paystubs_staff ON paystubs(staff_id, pay_period_year, pay_period_month);
